# .pages.yml — leme media PagesCMS config for luigisimiani.com
# Docs: https://pagescms.org/docs/configuration
# Managed by: leme media
# Structure: organized by page to match frontend components

media:
  - name: images
    label: Images
    input: public/images
    output: /images
    categories: [ image ]

content:
  # ─── Galleries ────────────────────────────────────────
  # Matches: Gallery page + Gallery detail page
  - name: galleries
    label: Galleries
    type: collection
    path: content/gallery
    format: json
    filename: "{primary}.json"
    fields:
      - name: id
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: subTitle
        label: Subtitle
        type: string
      - name: date
        label: Date
        type: date
      - name: coverPhoto
        label: Cover Photo
        type: image
        description: Main thumbnail for gallery list and fallback for Featured Work
      - name: featuredImage
        label: Featured Image
        type: object
        description: Separate landscape/portrait images for the Featured Work grid
        fields:
          - name: desktop
            label: Desktop (Landscape)
            type: image
            description: Landscape image shown on desktop in Featured Work grid
          - name: mobile
            label: Mobile (Portrait)
            type: image
            description: Portrait image shown on mobile in Featured Work grid
      - name: imageUrls
        label: Photos
        type: image
        list: true
      - name: category
        label: Category
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: password
        label: Password
        type: string
        description: Leave empty for public galleries
    view:
      fields: [ title, date ]
      sort: [ date, title ]
      default:
        sort: date
        order: desc

  # ─── Home Page ────────────────────────────────────────
  # Matches: Home page → Home/HeroSlideshow, Home/FeaturedWork
  - name: home-hero-slideshow
    label: "Home: Hero Slideshow"
    type: file
    path: content/home/hero-slideshow.json
    format: json
    fields:
      - name: heroTitle
        label: Hero Title
        type: string
        description: Optional title displayed over the hero slideshow
      - name: galleries
        label: Hero Galleries
        type: string
        list: true
        description: Gallery IDs for the hero slideshow (uses cover photo from each gallery)

  - name: home-featured-work
    label: "Home: Featured Work"
    type: file
    path: content/home/featured-work.json
    format: json
    fields:
      - name: title
        label: Section Title
        type: string
        description: Title for the featured work section
      - name: galleries
        label: Work
        type: string
        list: true
        description: Gallery IDs to feature (uses featuredImage landscape/portrait or cover photo)

  - name: home-quotes
    label: "Home: Quotes"
    type: file
    path: content/home/quotes.json
    format: json
    fields:
      - name: quotes
        label: Quotes
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
            hidden: true
          - name: text
            label: Quote
            type: text
          - name: author
            label: Author
            type: string

  # ─── About Page ───────────────────────────────────────
  # Matches: About Me page → AboutMe/ScrollingQuote, AboutMe/FilmStrip
  - name: about-bio
    label: "About: Bio"
    type: file
    path: content/about/bio.json
    format: json
    fields:
      - name: paragraphs
        label: Paragraphs
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
            hidden: true
          - name: value
            label: Text
            type: text

  - name: about-film-strip
    label: "About: Film Strip"
    type: file
    path: content/about/film-strip.json
    format: json
    fields:
      - name: images
        label: Images
        type: object
        list: true
        fields:
          - name: url
            label: Image
            type: image
          - name: orientation
            label: Orientation
            type: string
          - name: aspectRatio
            label: Aspect Ratio
            type: number

  # ─── Contact Page ─────────────────────────────────────
  # Matches: Contact page → Contact/ContactPage, Contact/InfoBox
  - name: contact
    label: "Contact: Info"
    type: file
    path: content/contact/contact.json
    format: json
    fields:
      - name: email
        label: Email
        type: string
      - name: location
        label: Location
        type: string
      - name: instagram
        label: Instagram
        type: string
      - name: linkedin
        label: LinkedIn
        type: string

settings:
  content:
    merge: true
